config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users
  resources :courses do
    resources :students,    :except => [:index, :show]
    resources :evaluations, :except => [:index, :show]
    
    get 'student_evaluations',             to: 'student_evaluations#index'
    put 'student_evaluations/:student_id', to: 'student_evaluations#update'
    get 'student_statistics',              to: 'student_evaluations#statistics'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  # root for devise
  # root to: 'admin#index'
  root to: 'courses#index'


end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :student_evaluations, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :dni, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :email, presence: true, email: true
  validates :file_number, presence: true
  scope :present_students, -> (evaluation) { joins(:student_evaluations).where("evaluation_id =  ?", evaluation.id) }
  scope :passing_students, -> (evaluation) { Student.present_students(evaluation).joins("INNER JOIN evaluations ON student_evaluations.evaluation_id = evaluations.id").where("score >= passing_score") }
  scope :failed_students,  -> (evaluation) { Student.present_students(evaluation).joins("INNER JOIN evaluations ON student_evaluations.evaluation_id = evaluations.id").where("score <  passing_score") }
  scope :absent_students,  -> (evaluation) { where(course_id: evaluation.course_id).where.not(id: Student.present_students(evaluation).pluck(:id)) }

  def find_evaluation(evaluation)
    StudentEvaluation.find_by(evaluation_id: evaluation.id, student_id: id)
  end

  def delete_student_evaluation(student_evaluation)
    self.student_evaluations.delete(student_evaluation)
  end

  def score_value(evaluation)
    if not absent?(evaluation)
      find_evaluation(evaluation).score
    end
  end
  
  def passed?(evaluation)
    not absent?(evaluation) and (score_value(evaluation) >= evaluation.passing_score)
  end

  def failed?(evaluation)
    not absent?(evaluation) and (score_value(evaluation) < evaluation.passing_score)
  end
  
  def absent?(evaluation)
    not find_evaluation(evaluation)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: [:edit, :update, :destroy]
  before_action :set_course,  only: [:new, :create, :edit, :destroy, :update]

  # GET /students
  # GET /students.json
  # def index
  #   @students = Student.where(course: @course)
  # end

  # GET /students/1
  # GET /students/1.json
  # def show
  # end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    @student.course = @course

    respond_to do |format|
      if @student.save
        format.html { redirect_to course_path(@course), notice: t('controllers.student.created') }
        format.json { render :show, status: :created, location: course_student_path(@course) }
      else
        puts @student.errors.full_messages
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to course_path(@course), notice: t('controllers.student.updated') }
        format.json { render :show, status: :ok, location: course_student_path(@student.course, @student) }
      else
        puts @student.errors.full_messages
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course), notice: t('controllers.student.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def set_course
      @course = Course.find(params[:course_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :dni, :file_number, :email, :course_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for [@course, @student], :html => {:class => "ui form"} do |form| %>
  <% if student.errors.any? %>
    <div class="ui negative message">
      <h4>No se pudo guardar el alumno por los siguientes motivos:</h4>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="two fields">
    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, id: :student_first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, id: :student_last_name %>
    </div>
  </div>
  <div class="two fields">
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, id: :student_email %>
    </div>

    <div class="field">
      <%= form.label :dni %>
      <%= form.number_field :dni, id: :student_dni %>
    </div>
  </div>

  <div class="field">
    <%= form.label :file_number %>
    <%= form.text_field :file_number, id: :student_file_number %>
  </div>

  <div class="actions">
    <%= form.submit class: "ui button green" %>
  </div>

<% end %>

app/views/students/edit.html.erb
<div class="ui container">

  <div class="ui breadcrumb header">
    <%= link_to 'Cursadas', courses_path %>
      <span class="divider">/</span>
    <%= link_to sprintf("%s - %d", @course.name, @course.year), course_path(@course) %>
      <span class="divider">/</span>
    <%= link_to 'Editar alumno', edit_course_student_path(@course, @student) %>
  </div>

  <h1 class="ui header">Editar alumno</h1>
  <%= render 'form', student: @student %>

</div>

app/views/students/new.html.erb
<div class="ui container">

  <div class="ui breadcrumb header">
    <%= link_to 'Cursadas', courses_path %>
      <span class="divider">/</span>
    <%= link_to sprintf("%s - %d", @course.name, @course.year), course_path(@course) %>
      <span class="divider">/</span>
    <%= link_to 'Agregar alumno', new_course_student_path(@course) %>
  </div>

  <h1 class="ui header">Agregar alumno</h1>
  <%= render 'form', student: @student %>

</div>